//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_Login_Index_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_Login_Index_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Login\Index.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Login\Index.cshtml"
  
    ViewBag.Title = "ByteStore - Iniciar Sesión";


#line default
#line hidden

#line 3 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Login\Index.cshtml"
using (Html.BeginForm("Login", "Login"))
{
    

#line default
#line hidden

#line 4 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Login\Index.cshtml"
__o = Html.AntiForgeryToken();


#line default
#line hidden

#line 5 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Login\Index.cshtml"
                            



#line default
#line hidden

#line 6 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Login\Index.cshtml"
   __o = Html.ValidationSummary(true, "", new { @class = "text-danger" });


#line default
#line hidden

#line 7 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Login\Index.cshtml"
       __o = Html.LabelFor(model => model.CorreoElectronico, htmlAttributes: new { @class = "text control-label col-md-6" });


#line default
#line hidden

#line 8 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Login\Index.cshtml"
           __o = Html.EditorFor(model => model.CorreoElectronico, new { htmlAttributes = new { @class = "form-control" } });


#line default
#line hidden

#line 9 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Login\Index.cshtml"
           __o = Html.ValidationMessageFor(model => model.CorreoElectronico, "", new { @class = "text-danger" });


#line default
#line hidden

#line 10 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Login\Index.cshtml"
       __o = Html.LabelFor(model => model.Contrasenna, htmlAttributes: new { @class = "text control-label col-md-6" });


#line default
#line hidden

#line 11 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Login\Index.cshtml"
           __o = Html.PasswordFor(model => model.Contrasenna, new { @class = "form-control" });


#line default
#line hidden

#line 12 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Login\Index.cshtml"
           __o = Html.ValidationMessageFor(model => model.Contrasenna, "", new { @class = "text-danger" });


#line default
#line hidden

#line 13 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Login\Index.cshtml"
                                    __o = Url.Action("Create","Usuario");


#line default
#line hidden

#line 14 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Login\Index.cshtml"
      



#line default
#line hidden

#line 15 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Login\Index.cshtml"
        
}

#line default
#line hidden
DefineSection("Scripts", () => {


#line 16 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Login\Index.cshtml"
__o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden
});

}
}
}
