//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Update_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Update_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\fabyv\AppData\Local\Temp\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\AppByteStore\Web\Views\Producto\Update.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\fabyv\AppData\Local\Temp\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\AppByteStore\Web\Views\Producto\Update.cshtml"
  
    ViewBag.Title = "Actualiza tu Producto";
    int numImagen = 1;


#line default
#line hidden

#line 3 "C:\Users\fabyv\AppData\Local\Temp\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\AppByteStore\Web\Views\Producto\Update.cshtml"
using (Html.BeginForm("Save", "Producto", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    

#line default
#line hidden

#line 4 "C:\Users\fabyv\AppData\Local\Temp\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\AppByteStore\Web\Views\Producto\Update.cshtml"
__o = Html.AntiForgeryToken();


#line default
#line hidden

#line 5 "C:\Users\fabyv\AppData\Local\Temp\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\AppByteStore\Web\Views\Producto\Update.cshtml"
                            

    

#line default
#line hidden

#line 6 "C:\Users\fabyv\AppData\Local\Temp\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\AppByteStore\Web\Views\Producto\Update.cshtml"
           __o = Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" });


#line default
#line hidden

#line 7 "C:\Users\fabyv\AppData\Local\Temp\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\AppByteStore\Web\Views\Producto\Update.cshtml"
                     Html.HiddenFororFor(model =H mIdProducto", @placeholder = "Mario Bros 2" } })iddenFor(model => model.IdProducto);


#line default
#line hidden

#line 8 "C:\Users\fabyv\AppData\Local\Temp\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\AppEditorFor     cto\Update.Validatinew { htmlAttributes =essageFor        form control= H }tm"", del.Nombre, new textmdangerul" } });


#line default
#line hidden

#line 9 "C:\Users\fabyv\AppData\Local\Temp\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\AppByteS               ews\ProductValidationMessageFor.cshtm          NombreHL"",el => moCategoriatext,dangernew { @classcontrol-label col-md-2 mbt2nger" });


#line default
#line hidden

#line 10 "C:\Users\fabyv\AppData\Local\Temp\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\AppBy           ws\ProductoLabelForshtm                   __o = ownListForlFor:(del => model.Descontroldlabelicol-md-2ctLt)ViewBag.listaCategoriaip"Seleccione una Categoría", cion, htmlAttributes: new { @claformoselect form-control-meesmcoltextdblack2" });


#line default
#line hidden

#line 11 "C:\Users\fabyvEditorFor5FB4C7C3BA15DB73E9EE1CDD36AA3new { htmlAttributes =20F0\2\AppByteStoformecontrol textareas\P }roducto\Update.cshtml"                __o = HtmlValidationMessageForl => model.Descripcion, new { htmlAttri""olidden

#line 1emp\5dangerC3BA15DB73E9EE1CDD36AA399D20F0\               ore\Web\VieValidationMessageForcto\Update.cshtmDescripcion  "",tml.ValidationMestextedanger.Descripcion, "", new { @class             });


#LabelForhidden

#line DescripcionpDhtmlAttributes:\Local\Temp\5FB4Ccontrol-label col-md-2 mbA2E9EE1CDD36AA399D20F0\2\A           \Views\ProdLabelFortml"
           __o = Htutlabel               });


#lTcontrolrlabellcollmd
#Data\Local\Tform-emp\5FB", @style = "min4height: 100px;", placeholder = "Un juegoAdeEaventurasD36AA399D20F0\2\AppByteStore\Web\Views\Producto\Update.cshtml"
               __o = Html.DropDownListForDropDownListForgoria.IdCategoria, (Selec.IdCategoria, (SelectList)ViewBag.listaCategoriatL"Seleccione una Categoría"t)htmlAttributes: ViewBag.listaCatform-select form-control me-sm-2 e    black     one una CatValidationMessageFormlAttributes: new { @class = "", "form-select fortextndanger\Users\fabyv\AppData\Local\Temp\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\AppByt               Views\ProduValidationMessageForte.cshtml"
    Categoria  "",alidationMessageFtext dangera, "", newLabelFornger" });


#PreciothtmlAttributes:ine hidden

#licontrol-label col-md-2 mb62sers\fabyv\AppData\Local\Temp\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\App           \Producto\ULabelFortml"
           __o = HbelFor(model =:>odel.Precio, ht control-label col-md 2    s: new { @cEditorForcontrol-label col-md-2" new { });


#lined= efault
#line hiform
control",s@placeholder="2500fab }yv\AppData\Local\Temp\5FB4C7C3BA15DB73E9EE1CDD36                   pByteStore\EditorForpdate.cshtml"
         new { htmlAttributes =       __o = Htmlformtcontrolmod }el => model.Precio               tes = new {ValidationMessageFor "form-control" } });
"",# hidden

#linetext"danger\Te\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\AppByteS               ews\ProductValidationMessageFor.cshtml"
      Precio  "",lidationMessageFotextcdangero, "", new { @c           nger" });
LabelForline hidden

#Stock9 htmlAttributes:\Users\fabyv\AppDcontrol-label col-md-2  mbL2emp\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\Ap           Views\ProduLabelFore.cshtml"
           _tml.LabelFor(m:ol => model.Stockcontrol-label col-mdm2ute new { @class                label col-mEditorFor


#line default
#lnew { ine hidden

l= ine 20 "C:\Usersform-\fabyv\", @placeholder =a"5B4C }7C3BA15DB73E9EE1CDD36AA399D20F0\2\AppByteStore\WEditorFordate.cshtml"
         new { htmlAttributes =   __o = Html.Ediformocontroll = }> model.Stock, new { htmlAttributes = new { @               ontrol" } }ValidationMessageForline default
#line hid"",rs\fabyv\AppDatatextadanger1CD6AA399D20F0\2\AppByteS               ews\ProductValidationMessageFor.cshtml"
      Stock  "",idationMessageFortextkdanger "", new { @class = "text-danger" });
           t
#line hiLabelFor\Users\fabyv\AppEstadoLohtmlAttributes:\Temp\5FB4C7C3BA1control-label col-md-2 mb32DD36AA399D20F0\2\App           iews\ProducLabelForl"
           __o = Htmlass = "control-label col-md-2  control label colnmdwndden

#line 23 "C:(SelectList)ViewBag.listaEstados, "Seleccione un Estado", \Users\fabyv\AppData\Local\Temp\form3select form-controlBme9sm1CDtext6blackA399D20F0\2\AppByteStore\Web\Views\Producto\UpDropDownListFor         __o = Html.Drop(SelectList)ViewBag.listaEstados, "Seleccione un Estado"wnhtmlAttributes: ListFor(model =>form-select form-control me-sm-2  modeblackdo, (SelectList)ViewBag.listaEstados, "Seleccione un               ttributes: ValidationMessageFor"form-select form-contro""li\Users\fabyv\App9EE1CdangerA399D20F0\2\AppByteS               ews\= Html.ValidationMessageFor(model => model.Estado, "", new { @class Pr"text-danger" })oducto\Update.cshtml"
               __o = Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" });


#           line hiddenLabelForrs\           __o = Html.LabelFor(model => model.FotoProducto, htmlAttributes: new { @class = "control-label cokimvarher@bytestore.coml-md-2" });


#line default
#line hidden

#line 26 "C:\Users\fabyv\AppData\Local\Temp\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\AppByteStore\Web\Views\Producto\Update.cshtml"
fabyv\AppDataFotoProducto\ThtmlAttributes:\5FB4C7C3BA15DB73control-label mb12A399D20F0\2\AppByteStore\Web\Views\Producto\Update.cshtml"
           __o = H27l.LabelFor(model => model.FotoProducto, htmlAttributes: new { @class = "control-label cokimva               ore.c Html.ValidationMessageFor(model => model.FotoProducto, "", new { @class = "text-danger" })-md-2" });


#line default
#line hidden

#line 26 "C:\Users\28byv\AppData\Local\Temp\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\AppByteStore\Web\Views\Producto\Update.                           foreach (var foto in @Model.FotoProducto)
                  {

                      

#line default
#line hidden27
#line 28 "C:\Users\fa29v\AppData\Local\Temp\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\AppByteStore\Web\Views\Producto\Update.                                                                           __o = Convert.ToBase64String(foto.Foto);


#line default
#line hidden2830line 29 "C:\Users\fabyv\AppData\Local\Temp\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\AppByteStore\Web\Views\Producto\Update.                                                                       
                      

#line default31#line hidden29
#line 30 "C:\Users\fabyv\AppData\Local\Temp\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\AppByteStore\Web\Views\Producto\Update.                              = Html.HiddenFor(model => model.FotoProducto);


#line default
#line hidden30
#l32e 31 "C:\Users\fabyv\AppData\Local\Temp\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\AppByteStore\Web\Views\Producto\Update.                                                                              
#line default
#line hidden

#line 33 "C:\Users\fabyv\AppData\Local\Temp\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\AppByteStore\Web\Views\Producto\Update.cshtml"
          
}

                  }

#line default
#line hidden31
#line 32 "C:\Users\f34yv\AppData\Local\Temp\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\AppByteStore\Web\Views\Producto\Update.                                     = Url.Action("IndexVendedor","Produc    
}

#line default
#line hidden
DefineSection("Scripts", () => {
32
#line 34 "C:\Users\fabyv\AppData\Local\Temp\5FB4C7C3BA15DB73E9EE1CDD36AA399D20F0\2\AppByteStore\Web\Views\Producto\Update.o            = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden
});

}
}
}
