//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompraDetalle
    {
        public int IdCompraEncabezado { get; set; }
        public int IdProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<bool> EstadoEntrega { get; set; }
    
        public virtual CompraEncabezado CompraEncabezado { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
