//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(CompraDetalleMetadata))]
    public partial class CompraDetalle
    {
        public int IdCompraEncabezado { get; set; }
        public int IdProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<bool> EstadoEntrega { get; set; }
    
        public virtual CompraEncabezado CompraEncabezado { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
