//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Direccion()
        {
            this.CompraEncabezado = new HashSet<CompraEncabezado>();
        }
    
        public int IdDireccion { get; set; }
        public Nullable<int> Provincia { get; set; }
        public Nullable<int> Canton { get; set; }
        public Nullable<int> Distrito { get; set; }
        public string Sennas { get; set; }
        public string Telefono { get; set; }
        public Nullable<bool> Tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompraEncabezado> CompraEncabezado { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
