//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FotoProducto
    {
        public int IdFotoProducto { get; set; }
        public byte[] Foto { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
