//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int IdFacturaEncabezado { get; set; }
        public Nullable<int> EstadoEntrega { get; set; }
    
        public virtual Direccion Direccion { get; set; }
        public virtual FacturaEncabezado FacturaEncabezado { get; set; }
    }
}
