//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        public int IdTelefono { get; set; }
        public string Numero { get; set; }
        public Nullable<bool> Tipo { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
