//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_Pedido_Details_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_Pedido_Details_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
  
    ViewBag.Title = "ByteStore - Tu Pedido";


#line default
#line hidden

#line 3 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
            __o = Url.Action("Index", "Pedido");


#line default
#line hidden

#line 4 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CompraEncabezado.IdCompraEncabezado);


#line default
#line hidden

#line 5 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
           __o = Html.DisplayFor(model => model.CompraEncabezado.IdCompraEncabezado);


#line default
#line hidden

#line 6 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CompraEncabezado.FechaHora);


#line default
#line hidden

#line 7 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
           __o = Html.DisplayFor(model => model.CompraEncabezado.FechaHora);


#line default
#line hidden

#line 8 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.EstadoEntrega);


#line default
#line hidden

#line 9 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
            if (Model.EstadoEntrega == 0)
            {
            

#line default
#line hidden

#line 10 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
                   
            }
            else if (Model.EstadoEntrega == 1)
            {
            

#line default
#line hidden

#line 11 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
                   
            }
            else
            {
            

#line default
#line hidden

#line 12 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
                   
            }

#line default
#line hidden

#line 13 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CompraEncabezado.Direccion);


#line default
#line hidden

#line 14 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
           __o = Html.DisplayFor(model => model.CompraEncabezado.Direccion.Sennas);


#line default
#line hidden

#line 15 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CompraEncabezado.MetodoPago);


#line default
#line hidden

#line 16 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
           __o = Model.CompraEncabezado.MetodoPago.Proveedor;


#line default
#line hidden

#line 17 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                         __o = Model.CompraEncabezado.MetodoPago.TipoPago.Descripcion;


#line default
#line hidden

#line 18 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                                                                                    __o = Html.DisplayFor(model => model.CompraEncabezado.MetodoPago.FechaExpiracion);


#line default
#line hidden

#line 19 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                   __o = Html.DisplayNameFor(model => model.CompraEncabezado.CompraDetalle);


#line default
#line hidden

#line 20 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
                foreach (var detalle in (ICollection<Infraestructure.Models.CompraDetalle>)Model.CompraEncabezado.CompraDetalle)
                {
                

#line default
#line hidden

#line 21 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                           __o = detalle.Producto.Nombre;


#line default
#line hidden

#line 22 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
                   __o = Html.DisplayFor(model => detalle.Precio);


#line default
#line hidden

#line 23 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
                   __o = detalle.Cantidad;


#line default
#line hidden

#line 24 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
                    if (detalle.EstadoEntrega == false)
                        {
                    

#line default
#line hidden

#line 25 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                         
                        }
                        else
                        {
                    

#line default
#line hidden

#line 26 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                      
                        }

#line default
#line hidden

#line 27 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
                     
                }

#line default
#line hidden

#line 28 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CompraEncabezado.SubTotal);


#line default
#line hidden

#line 29 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
           __o = Html.DisplayFor(model => model.CompraEncabezado.SubTotal);


#line default
#line hidden

#line 30 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CompraEncabezado.Impuesto);


#line default
#line hidden

#line 31 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
           __o = Html.DisplayFor(model => model.CompraEncabezado.Impuesto);


#line default
#line hidden

#line 32 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CompraEncabezado.Total);


#line default
#line hidden

#line 33 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
           __o = Html.DisplayFor(model => model.CompraEncabezado.Total);


#line default
#line hidden

#line 34 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
      
        ApplicationCore.Services.IServiceEvaluacion serviceEvaluacion = new ApplicationCore.Services.ServiceEvaluacion();
        IEnumerable<Infraestructure.Models.Evaluacion> evaluaciones = serviceEvaluacion.GetEvaluacionByPedidoForCliente(Model.IdCompraEncabezado, Model.CompraEncabezado.Usuario.IdUsuario);
        IEnumerable<object> evaluados = Model.CompraEncabezado.CompraDetalle.Select(cd => new { IdUsuario = cd.Producto.Usuario.IdUsuario, Nombre = $"{cd.Producto.Usuario.Nombre} {cd.Producto.Usuario.PrimerApellido} {cd.Producto.Usuario.SegundoApellido}" }).Distinct().ToList();
    

#line default
#line hidden

#line 35 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
    if (Model.EstadoEntrega == 2)
    {
    

#line default
#line hidden

#line 36 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
          
    }

#line default
#line hidden

#line 37 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
        if (evaluaciones.Count() > 0 && Model.EstadoEntrega == 2)
        {

        

#line default
#line hidden

#line 38 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
   __o = Html.Partial("_PartialEvaluacionPedido", evaluaciones);


#line default
#line hidden

#line 39 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                               
        }

#line default
#line hidden

#line 40 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
        if(Model.EstadoEntrega == 2 && evaluados.Count() != evaluaciones.Count())
        {
        

#line default
#line hidden

#line 41 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                 
        

#line default
#line hidden

#line 42 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                                                   __o = Model.IdCompraEncabezado;


#line default
#line hidden

#line 43 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                                                                                                 __o = ((Infraestructure.Models.Usuario)Session["User"]).IdUsuario;


#line default
#line hidden

#line 44 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                                                                                                                                                                                                                                     
        }

#line default
#line hidden
DefineSection("Scripts", () => {


#line 45 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
__o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden

#line 46 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
                       __o = Html.Raw(Json.Encode(evaluados));


#line default
#line hidden

#line 47 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\4\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                        __o = Html.Raw(Web.Util.SweetAlertHelper.Mensaje("Cuidado", "Debe calificar al cliente", Web.Util.SweetAlertMessageType.warning));


#line default
#line hidden
});

}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Views_Pedido_Details_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Views_Pedido_Details_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
  
    ViewBag.Title = "ByteStore - Tu Pedido";


#line default
#line hidden

#line 3 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
            __o = Url.Action("Index", "Pedido");


#line default
#line hidden

#line 4 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CompraEncabezado.IdCompraEncabezado);


#line default
#line hidden

#line 5 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
           __o = Html.DisplayFor(model => model.CompraEncabezado.IdCompraEncabezado);


#line default
#line hidden

#line 6 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CompraEncabezado.FechaHora);


#line default
#line hidden

#line 7 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
           __o = Html.DisplayFor(model => model.CompraEncabezado.FechaHora);


#line default
#line hidden

#line 8 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.EstadoEntrega);


#line default
#line hidden

#line 9 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
            if (Model.EstadoEntrega == 0)
            {
            

#line default
#line hidden

#line 10 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
                   
            }
            else if (Model.EstadoEntrega == 1)
            {
            

#line default
#line hidden

#line 11 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
                   
            }
            else
            {
            

#line default
#line hidden

#line 12 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
                   
            }

#line default
#line hidden

#line 13 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CompraEncabezado.Direccion);


#line default
#line hidden

#line 14 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
           __o = Html.DisplayFor(model => model.CompraEncabezado.Direccion.Sennas);


#line default
#line hidden

#line 15 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CompraEncabezado.MetodoPago);


#line default
#line hidden

#line 16 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
           __o = Model.CompraEncabezado.MetodoPago.Proveedor;


#line default
#line hidden

#line 17 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                         __o = Model.CompraEncabezado.MetodoPago.TipoPago.Descripcion;


#line default
#line hidden

#line 18 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                                                                                    __o = Html.DisplayFor(model => model.CompraEncabezado.MetodoPago.FechaExpiracion);


#line default
#line hidden

#line 19 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                   __o = Html.DisplayNameFor(model => model.CompraEncabezado.CompraDetalle);


#line default
#line hidden

#line 20 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
                foreach (var detalle in (ICollection<Infraestructure.Models.CompraDetalle>)Model.CompraEncabezado.CompraDetalle)
                {
                

#line default
#line hidden

#line 21 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                           __o = detalle.Producto.Nombre;


#line default
#line hidden

#line 22 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
                   __o = Html.DisplayFor(model => detalle.Precio);


#line default
#line hidden

#line 23 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
                   __o = detalle.Cantidad;


#line default
#line hidden

#line 24 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
                    if (detalle.EstadoEntrega == false)
                        {
                    

#line default
#line hidden

#line 25 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                         
                        }
                        else
                        {
                    

#line default
#line hidden

#line 26 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                      
                        }

#line default
#line hidden

#line 27 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
                     
                }

#line default
#line hidden

#line 28 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CompraEncabezado.SubTotal);


#line default
#line hidden

#line 29 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
           __o = Html.DisplayFor(model => model.CompraEncabezado.SubTotal);


#line default
#line hidden

#line 30 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CompraEncabezado.Impuesto);


#line default
#line hidden

#line 31 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
           __o = Html.DisplayFor(model => model.CompraEncabezado.Impuesto);


#line default
#line hidden

#line 32 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CompraEncabezado.Total);


#line default
#line hidden

#line 33 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
           __o = Html.DisplayFor(model => model.CompraEncabezado.Total);


#line default
#line hidden

#line 34 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
      
        ApplicationCore.Services.IServiceEvaluacion serviceEvaluacion = new ApplicationCore.Services.ServiceEvaluacion();
        IEnumerable<Infraestructure.Models.Evaluacion> evaluaciones = serviceEvaluacion.GetEvaluacionByPedidoForCliente(Model.IdCompraEncabezado, Model.CompraEncabezado.Usuario.IdUsuario);
        IEnumerable<object> evaluados = Model.CompraEncabezado.CompraDetalle.Select(cd => new { IdUsuario = cd.Producto.Usuario.IdUsuario, Nombre = $"{cd.Producto.Usuario.Nombre} {cd.Producto.Usuario.PrimerApellido} {cd.Producto.Usuario.SegundoApellido}" }).Distinct().ToList();
    

#line default
#line hidden

#line 35 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
    if (Model.EstadoEntrega == 2)
    {
    

#line default
#line hidden

#line 36 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
          
    }

#line default
#line hidden

#line 37 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
        if (evaluaciones.Count() > 0 && Model.EstadoEntrega == 2)
        {

        

#line default
#line hidden

#line 38 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
   __o = Html.Partial("_PartialEvaluacionPedido", evaluaciones);


#line default
#line hidden

#line 39 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                               
        }

#line default
#line hidden

#line 40 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
        if(Model.EstadoEntrega == 2 && evaluados.Count() != evaluaciones.Count())
        {
        

#line default
#line hidden

#line 41 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                 
        

#line default
#line hidden

#line 42 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                                                   __o = Model.IdCompraEncabezado;


#line default
#line hidden

#line 43 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                                                                                                 __o = ((Infraestructure.Models.Usuario)Session["User"]).IdUsuario;


#line default
#line hidden

#line 44 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                                                                                                                                                                                                                                     
        }

#line default
#line hidden
DefineSection("Scripts", () => {


#line 45 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
__o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden

#line 46 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
                       __o = Html.Raw(Json.Encode(evaluados));


#line default
#line hidden

#line 47 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\3\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                        __o = Html.Raw(Web.Util.SweetAlertHelper.Mensaje("Cuidado", "Debe calificar al cliente", Web.Util.SweetAlertMessageType.warning));


#line default
#line hidden
});

}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Details_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Details_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
__o = model;


#line default
#line hidden

#line 2 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
  
    ViewBag.Title = "ByteStore - Tu Pedido";


#line default
#line hidden

#line 3 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
            __o = Url.Action("Index", "Pedido");


#line default
#line hidden

#line 4 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CompraEncabezado.IdCompraEncabezado);


#line default
#line hidden

#line 5 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
           __o = Html.DisplayFor(model => model.CompraEncabezado.IdCompraEncabezado);


#line default
#line hidden

#line 6 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CompraEncabezado.FechaHora);


#line default
#line hidden

#line 7 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
           __o = Html.DisplayFor(model => model.CompraEncabezado.FechaHora);


#line default
#line hidden

#line 8 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.EstadoEntrega);


#line default
#line hidden

#line 9 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
            if (Model.EstadoEntrega == 0)
            {
            

#line default
#line hidden

#line 10 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
                   
            }
            else if (Model.EstadoEntrega == 1)
            {
            

#line default
#line hidden

#line 11 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
                   
            }
            else
            {
            

#line default
#line hidden

#line 12 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
                   
            }

#line default
#line hidden

#line 13 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CompraEncabezado.Direccion);


#line default
#line hidden

#line 14 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
           __o = Html.DisplayFor(model => model.CompraEncabezado.Direccion.Sennas);


#line default
#line hidden

#line 15 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CompraEncabezado.MetodoPago);


#line default
#line hidden

#line 16 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
           __o = Model.CompraEncabezado.MetodoPago.Proveedor;


#line default
#line hidden

#line 17 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                         __o = Model.CompraEncabezado.MetodoPago.TipoPago.Descripcion;


#line default
#line hidden

#line 18 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                                                                                    __o = Html.DisplayFor(model => model.CompraEncabezado.MetodoPago.FechaExpiracion);


#line default
#line hidden

#line 19 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                   __o = Html.DisplayNameFor(model => model.CompraEncabezado.CompraDetalle);


#line default
#line hidden

#line 20 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
                foreach (var detalle in (ICollection<Infraestructure.Models.CompraDetalle>)Model.CompraEncabezado.CompraDetalle)
                {
                

#line default
#line hidden

#line 21 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                           __o = detalle.Producto.Nombre;


#line default
#line hidden

#line 22 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
                   __o = Html.DisplayFor(model => detalle.Precio);


#line default
#line hidden

#line 23 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
                   __o = detalle.Cantidad;


#line default
#line hidden

#line 24 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
                    if (detalle.EstadoEntrega == false)
                        {
                    

#line default
#line hidden

#line 25 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                         
                        }
                        else
                        {
                    

#line default
#line hidden

#line 26 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                      
                        }

#line default
#line hidden

#line 27 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
                     
                }

#line default
#line hidden

#line 28 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CompraEncabezado.SubTotal);


#line default
#line hidden

#line 29 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
           __o = Html.DisplayFor(model => model.CompraEncabezado.SubTotal);


#line default
#line hidden

#line 30 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CompraEncabezado.Impuesto);


#line default
#line hidden

#line 31 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
           __o = Html.DisplayFor(model => model.CompraEncabezado.Impuesto);


#line default
#line hidden

#line 32 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
       __o = Html.DisplayNameFor(model => model.CompraEncabezado.Total);


#line default
#line hidden

#line 33 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
           __o = Html.DisplayFor(model => model.CompraEncabezado.Total);


#line default
#line hidden

#line 34 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
      
        ApplicationCore.Services.IServiceEvaluacion serviceEvaluacion = new ApplicationCore.Services.ServiceEvaluacion();
        IEnumerable<Infraestructure.Models.Evaluacion> evaluaciones = serviceEvaluacion.GetEvaluacionByPedidoForCliente(Model.IdCompraEncabezado, Model.CompraEncabezado.Usuario.IdUsuario);
        IEnumerable<object> evaluados = Model.CompraEncabezado.CompraDetalle.Select(cd => new { IdUsuario = cd.Producto.Usuario.IdUsuario, Nombre = $"{cd.Producto.Usuario.Nombre} {cd.Producto.Usuario.PrimerApellido} {cd.Producto.Usuario.SegundoApellido}" }).Distinct().ToList();
    

#line default
#line hidden

#line 35 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
    if (Model.EstadoEntrega == 2)
    {
    

#line default
#line hidden

#line 36 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
          
    }

#line default
#line hidden

#line 37 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
        if (evaluaciones.Count() > 0 && Model.EstadoEntrega == 2)
        {

        

#line default
#line hidden

#line 38 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
   __o = Html.Partial("_PartialEvaluacionPedido", evaluaciones);


#line default
#line hidden

#line 39 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                               
        }

#line default
#line hidden

#line 40 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
        if(Model.EstadoEntrega == 2 && evaluados.Count() != evaluaciones.Count())
        {
        

#line default
#line hidden

#line 41 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                 
        

#line default
#line hidden

#line 42 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                                                   __o = Model.IdCompraEncabezado;


#line default
#line hidden

#line 43 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                                                                                                 __o = ((Infraestructure.Models.Usuario)Session["User"]).IdUsuario;


#line default
#line hidden

#line 44 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                                                                                                                                                                                                                                                     
        }

#line default
#line hidden
DefineSection("Scripts", () => {


#line 45 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
__o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden

#line 46 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
                       __o = Html.Raw(Json.Encode(evaluados));


#line default
#line hidden

#line 47 "C:\Users\Estudiante\AppData\Local\Temp\7B21E5802F435DFBCD6D7C0B03B5EA5ECBD2\2\AppByteStore\Web\Views\Pedido\Details.cshtml"
                                        __o = Html.Raw(Web.Util.SweetAlertHelper.Mensaje("Cuidado", "Debe calificar al cliente", Web.Util.SweetAlertMessageType.warning));


#line default
#line hidden
});

}
}
}
