//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_ReportesAdmin_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_ReportesAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Estudiante\AppData\Local\Temp\5CE65DBC8A4624DC0BB18FADA42D96947E0B\4\AppByteStore\Web\Views\Reportes\ReportesAdmin.cshtml"
  
    ViewBag.Title = "Reporte de Compras";


#line default
#line hidden
DefineSection("Scripts", () => {

});

}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_ReportesAdmin_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_ReportesAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Estudiante\AppData\Local\Temp\5CE65DBC8A4624DC0BB18FADA42D96947E0B\3\AppByteStore\Web\Views\Reportes\ReportesAdmin.cshtml"
  
    ViewBag.Title = "Reporte de Compras";


#line default
#line hidden
DefineSection("Scripts", () => {

});

}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_ReportesAdmin_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_ReportesAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Estudiante\AppData\Local\Temp\5CE65DBC8A4624DC0BB18FADA42D96947E0B\2\AppByteStore\Web\Views\Reportes\ReportesAdmin.cshtml"
  
    ViewBag.Title = "Reporte de Compras";


#line default
#line hidden
DefineSection("Scripts", () => {

});

}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_ReportesAdmin_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_ReportesAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\elias\AppData\Local\Temp\955932BC901F98DED9610CD6ABEDAD3A305A\2\AppByteStore\Web\Views\Reportes\ReportesAdmin.cshtml"
  
    ViewBag.Title = "Reporte de Compras";


#line default
#line hidden
DefineSection("Scripts", () => {

});

}
}
}
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_ReportesAdmin_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_ReportesAdmin_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\elias\AppData\Local\Temp\5EA73A94D56B70907A95670590C275E56CB9\2\AppByteStore\Web\Views\Reportes\ReportesAdmin.cshtml"
  
    ViewBag.Title = "Reporte de Compras";


#line default
#line hidden
DefineSection("Scripts", () => {


#line 2 "C:\Users\elias\AppData\Local\Temp\5EA73A94D56B70907A95670590C275E56CB9\2\AppByteStore\Web\Views\Reportes\ReportesAdmin.cshtml"
__o = Scripts.Render("~/bundles/jqueryval");


#line default
#line hidden

#line 3 "C:\Users\elias\AppData\Local\Temp\5EA73A94D56B70907A95670590C275E56CB9\2\AppByteStore\Web\Views\Reportes\ReportesAdmin.cshtml"
__o = ;


#line default
#line hidden
});

}
}
}
